name: Install Zip Package

on:
  push:
    branches:
      - Zip-buffer

jobs:
  build:
    runs-on: ubuntu-2024.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache APT packages
        uses: actions/cache@v2
        with:
          path: /var/cache/apt
          key: ${{ runner.os }}-apt
          restore-keys: ${{ runner.os }}-apt

      - name: Cache APT lists
        uses: actions/cache@v2
        with:
          path: /var/lib/apt/lists
          key: ${{ runner.os }}-apt-lists
          restore-keys: ${{ runner.os }}-apt-lists

      - name: Update APT and Install Zip
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y zip

      - name: Verify Zip Installation
        run: |
          zip --version
          echo "Zip is installed and available."
